name: Full lifecycle for Mule app
on: 
    workflow_dispatch:
        inputs:
            mule-env:
                description: Mulesoft environment to deploy
                required: true
                default: 'sandbox'
jobs:
    sandbox:
        if: github.event.inputs.mule-env == 'sandbox'
        runs-on: ubuntu-latest
        steps:
            # Information about the workflow run (context).
            - name: Get GitHub object
              env:
                GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo "$GITHUB_CONTEXT"
            # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
            - name: Get the code
              uses: actions/checkout@v4
            - name: Check repo
              run: ls
            - name: Set up JDK 8
              uses: actions/setup-java@v4
              with:
                distribution: 'adopt'
                java-version: '8'
                cache: 'maven'
                cache-dependency-path: 'pom.xml'

              


