name: ci_cd_pipeline_with_composite_action
on: 
    workflow_dispatch:
        inputs:
            mule-env:
                description: Mulesoft environment to deploy
                required: true
                default: 'sandbox'
jobs:
    sandbox:
        runs-on: ubuntu-latest
        if: github.event.inputs.mule-env == 'sandbox'
        steps:
            - name: Test, Build and Deploy
              uses: ./.github/actions/build
              with: 
                GITHUB_ENV: "sandbox"
                CLOUDHUB_ENVIRONMENT: "Sandbox" 
                CLOUDHUB_REGION: "us-east-2"
                CLOUDHUB_ID: ${{ secrets.CLOUDHUB_ID }}
                CLOUDHUB_SECRET: ${{ secrets.CLOUDHUB_SECRET }}
    design:
        runs-on: ubuntu-latest
        if: github.event.inputs.mule-env == 'design'
        steps:
            - name: Test, Build and Deploy
              uses: ./.github/actions/build
              with: 
                GITHUB_ENV: "design"
                CLOUDHUB_ENVIRONMENT: "Design" 
                CLOUDHUB_REGION: "us-east-2"
                CLOUDHUB_ID: ${{ secrets.CLOUDHUB_ID }}
                CLOUDHUB_SECRET: ${{ secrets.CLOUDHUB_SECRET }}       