name: Full lifecycle for Mule app
on: 
    workflow_dispatch:
        inputs:
            mule-env:
                description: Mulesoft environment to deploy
                required: true
                default: 'sandbox'
jobs:
    sandbox:
        if: github.event.inputs.mule-env == 'sandbox'
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Get the code
              uses: actions/checkout@v4
              with:
                ref:${{ github.event.ref }}      


