name: sandbox_ci_cd_pipeline
on: workflow_dispatch

jobs:
    sandbox:
        uses: ./.github/workflows/reusable.yml
        with: 
            GITHUB_ENV: "sandbox"
            CLOUDHUB_ENVIRONMENT: "Sandbox" 
            CLOUDHUB_REGION: "us-east-2"
            CLOUDHUB_ID: ${{ secrets.CLOUDHUB_ID }}
            CLOUDHUB_SECRET: ${{ secrets.CLOUDHUB_SECRET }}